Fixed X11 problem on server but still JSON error
Online server not reachable: A message body writer for Java type, class
com.lefrantguillaume.networkComponent.dataServerComponent.InitServerSnd,
 and MIME media type, application/json, was not found
com.sun.jersey.api.client.ClientHandlerException:
com.sun.jersey.api.client.ClientHandlerException: A message body writer
for Java type, class
com.lefrantguillaume.networkComponent.dataServerComponent.InitServerSnd,
 and MIME media type, application/json, was not found
	at
com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(UR
LConnectionClientHandler.java:149)
	at
com.sun.jersey.api.client.filter.HTTPBasicAuthFilter.handle(HTTPBasicAut
hFilter.java:81)
	at com.sun.jersey.api.client.Client.handle(Client.java:648)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:670)
	at
com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at
com.sun.jersey.api.client.WebResource$Builder.post(WebResource.java:563)
	at
com.lefrantguillaume.networkComponent.dataServerComponent.DataServer.get
ClientResponse(DataServer.java:71)
	at
com.lefrantguillaume.networkComponent.dataServerComponent.DataServer.ini
tServer(DataServer.java:81)
	at
com.lefrantguillaume.master.MasterController$1.lambda$run$15(MasterContr
oller.java:99)
	at com.lefrantguillaume.utils.CallbackTask.run(CallbackTask.java:16)
	at
com.lefrantguillaume.master.MasterController$1.run(MasterController.java
:123)
Caused by: com.sun.jersey.api.client.ClientHandlerException: A message
body writer for Java type, class
com.lefrantguillaume.networkComponent.dataServerComponent.InitServerSnd,
 and MIME media type, application/json, was not found
	at
com.sun.jersey.api.client.RequestWriter.writeRequestEntity(RequestWriter
.java:288)
	at
com.sun.jersey.client.urlconnection.URLConnectionClientHandler._invoke(U
RLConnectionClientHandler.java:204)
	at
com.sun.jersey.client.urlconnection.URLConnectionClientHandler.handle(UR
LConnectionClientHandler.java:147)
	... 10 more
Exception in thread "Thread-3" java.lang.NullPointerException
	at
com.lefrantguillaume.master.MasterController$1.lambda$run$16(MasterContr
oller.java:105)
	at com.lefrantguillaume.utils.CallbackTask.run(CallbackTask.java:17)
	at
com.lefrantguillaume.master.MasterController$1.run(MasterController.java
:123)